/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Charlie
 */
public class Jfcronometro extends javax.swing.JFrame {

    /**
     * Creates new form Jfcronometro
     */
    
    //crear variables del tiempo
    private Timer tiempo;
    private int centesimas =0;
    private int segundos = 0;
    private int minutos = 0;
    private int horas = 0;
    
    private ActionListener acciones = new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e){
            centesimas ++;
            if (centesimas == 99){
                segundos ++;
                centesimas = 0;
            }
            if (segundos == 59){
                minutos ++;
                segundos = 0;
            }
            if (minutos == 59){
                horas ++;
                minutos = 0;
            }
            if (horas == 24){
                horas =0;
            }
            actualizarTiempo();
         }  
    };
     
    private void actualizarTiempo(){
        String texto = (horas < 9? "0":"")+horas+":"+(minutos <9? "0":"")+minutos+":"+(segundos < 9? "0":"")+segundos+":"+(centesimas <9? "0":"")+centesimas;
        etiqueta_tiempo.setText(texto);
    }
    
    
    public Jfcronometro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cronometro");
        tiempo = new Timer (10,acciones);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_titulo = new javax.swing.JLabel();
        etiqueta_tiempo = new javax.swing.JLabel();
        boton_iniciar = new javax.swing.JButton();
        boton_pausar = new javax.swing.JButton();
        boton_detener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueta_titulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        etiqueta_titulo.setText("Cronometro");

        etiqueta_tiempo.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        etiqueta_tiempo.setText("00:00:00:00");

        boton_iniciar.setText("Iniciar");
        boton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_iniciarActionPerformed(evt);
            }
        });

        boton_pausar.setText("Pausar");
        boton_pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pausarActionPerformed(evt);
            }
        });

        boton_detener.setText("Detener");
        boton_detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_detenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(etiqueta_tiempo)
                        .addGap(43, 43, 43)
                        .addComponent(boton_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_detener, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_titulo)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_tiempo)
                    .addComponent(boton_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_detener, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_iniciarActionPerformed
        tiempo.start();
        boton_iniciar.setEnabled(false);
        boton_iniciar.setText("Reanudar");
        boton_pausar.setEnabled(true);
        boton_detener.setEnabled(true);
    }//GEN-LAST:event_boton_iniciarActionPerformed

    private void boton_detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_detenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
        }
        centesimas =0;
        segundos = 0;
        minutos = 0;
        horas = 0;
        actualizarTiempo();
        boton_iniciar.setText("Iniciar");
        boton_iniciar.setEnabled(true);
        boton_pausar.setEnabled(false);
        boton_detener.setEnabled(false);
        
        
    }//GEN-LAST:event_boton_detenerActionPerformed

    private void boton_pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pausarActionPerformed
        tiempo.stop();
        boton_iniciar.setEnabled(true);
    }//GEN-LAST:event_boton_pausarActionPerformed
     
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfcronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfcronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfcronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfcronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfcronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_detener;
    private javax.swing.JButton boton_iniciar;
    private javax.swing.JButton boton_pausar;
    private javax.swing.JLabel etiqueta_tiempo;
    private javax.swing.JLabel etiqueta_titulo;
    // End of variables declaration//GEN-END:variables
}
